#### Q. 파이썬 외장함수 random을 이용하여 아래사항들을 출력하세요.
- 0.0<= x <1.0 사이의 float를 랜덤하게 선택
- 10에서 20사이의 정수중에서 난수값 선택
- 10보다 적은 int 선택
- 20과 30사이의 float 선택
- [6,7,8,9,10 ]리스트 내부에 있는 요소를 랜덤하게 선택
- [6,7,8,9,10 ]리스트 내부에 있는 요소중 k개 선택

In [0]:
import random

#### Q. 주어진 데이터에서 랜덤으로 하나를 선택하여 꺼낸 다음 그 값을 출력하고 꺼내진 요소를 제외시킨 리스트를 출력하세요.
data = [1,2,3,4,5,6,7,8,9,10]

#### Q. 넘파이 random을 이용하여 아래사항들을 출력하세요.
- 0부터 10까지 랜덤한 숫자 1개
- 0부터 1사이의 균일분포에서 난수 5개로 구성되는 배열 생성
- 평균 0, 표준편차 1의 가우시안 표준정규분포에서 난수 10개로 구성되는 배열 생성

In [0]:
import numpy as np

#### Q. 넘파이 random을 이용하여 아래사항들을 출력하세요.
- [6,7,8,9,10] 리스트의 데이터의 순서 바꾸기

#### Q. 넘파이 random을 이용하여 아래사항들을 출력하세요.
- 10보다 적은 정수에서 랜덤으로 중복되지 않게 5개를 선택 배열을 생성하세요.
- c1 = [6,7,8,9,10] 배열에서 랜덤으로 중복 선택이 가능하게 5개를 선택, 배열을 생성하세요.

#### Q. 넘파이 random을 이용하여 2.0보다 크거나 3.0보다 작은 5개의 수를 출력하세요.

#### Q. 넘파이 random을 이용하여 0.0보다 크거나 1.0보다 작은 (3,3) 2차원 배열을 2가지 방식으로 출력하세요.

#### Q. 앞(head) 또는 뒤(tail) (n=1) 가 나올 확률이 각각 50%(p=0.5)인 동전 던지기를 20번(size=20) 수행한 결과를 배열로 출력하세요.

#### Q. (2,3,4) 3차원 배열 형태로 정규분포(np.random.normal)로 부터 무작위 샘플을 생성

#### Q. [4 7 7 1 9]에서 중복되지 않는 원소 배열과 각 원소의 중복 개수 배열을 출력하세요.

#### Q. [1, 1, 2, 2, 2, 3]에서 0 ~ 5에 해당하는 정수의 개수 배열을 출력하세요.

#### Q(응용) 'ID', 'Prod', 'Price' 3개의 column과 10개의 row으로 구성되는 데이터셋을 아래를 참조하여 생성하세요.
- ID는 1 ~ 10으로 적용
- Prod는 상품코드로서 np.random을 이용하여 10보다 적은 정수를 랜덤하게 선택
- Price는 가격으로서 np.random을 이용하여 1000 보다 적은 양의 소수를 랜덤하게 선택
- 3개의 컬럼을 결합하는 방법은 concat() 함수를 사용